baseURL = "https://oliviazhang-personal.netlify.app/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Olivia's"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "London Business School, Regent’s Park, London, NW1 4SA, United Kingdom "
author = "Xuan(Olivia) Zhang"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
email = "ozhang.mfa2021@london.edu"
google_analytics_id = ""
home = "Home"
logo = ""
phone = "+880 2544 658 256"
theme_color = "#41228e"
[params.contact]
enable = false
form_action = "#"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.526195"
map_longitude = "-0.160695"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[[params.social]]
URL = "https://www.facebook.com/profile.php?id=100006386222416"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.linkedin.com/in/olivia-xuan-zhang/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://github.com/oliviazhang-0111"
icon = "ti-github"
[[params.social]]
URL = "https://www.instagram.com/oliviacheung_/"
icon = "ti-instagram"
